import type { Metadata } from "next";
import './globals.css'
import { layoutPropsType } from "./type";

export const metadata: Metadata = {
  title: "MELLO - COFFEE | ملو کافی",
  description: "Generated by create next app",
};

export default function RootLayout({children}:layoutPropsType) {
  return (
    <html lang="en-fa">
      <body dir="rtl">
        {children}
      </body>
    </html>
  );
}
